"""add max_attempts to deliveries

Revision ID: 1d60ad2c3502
Revises: 516b4f66c012
Create Date: 2026-08-18 17:44:56.805498

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d60ad2c3502"
down_revision: str | Sequence[str] | None = "516b4f66c012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deliveries",
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("5"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deliveries", "max_attempts")
    # ### end Alembic commands ###
