"""...

Revision ID: aa012e9b9c06
Revises: 7c0fe5aaa2e0
Create Date: 2026-08-18 12:30:50.166874

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "aa012e9b9c06"
down_revision: str | Sequence[str] | None = "7c0fe5aaa2e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
